#version: '3.8'
version: '3.8'

services:
  moodle_db:
    image: mariadb:latest
    container_name: moodle_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodleuser
      - MYSQL_PASSWORD=moodlepassword
    volumes:
      - db_data:/var/lib/mysql

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    restart: always
    ports:
      - "8084:84" # Cambia si necesitas otro puerto
    environment:
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=moodle_db
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_PASSWORD=moodlepassword
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      - moodle_db

volumes:
  db_data:
  moodle_data:
