FROM bitnami/moodle:latest

# Instalar extensiones adicionales de PHP si es necesario
RUN install_packages php7-mysqli php7-xmlrpc php7-curl

# Copiar configuraciones personalizadas (opcional)
# COPY ./config/custom.ini /etc/php/7.4/cli/conf.d/custom.ini
