version: '3.8'

services:
  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    ports:
      - "8082:80" # Moodle estará disponible en http://localhost:8082
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=password
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: moodle_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  moodle_data:
  db_data:
