FROM wordpress:latest

# Instalar dependencias adicionales (opcional)
RUN apt-get update && apt-get install -y \
    vim \
    curl

# Copiar configuraciones personalizadas (si es necesario)
# COPY ./config/wp-config.php /var/www/html/wp-config.php
